version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.13-alpine
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_DEFAULT_VHOST=test
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s
